<a href="https://colab.research.google.com/github/user127386/AI-ML/blob/user127386/numpy_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
sales_lists = [120, 150, 300, 250, 90]
sales_array = np.array(sales_lists)
print(sales_lists)
print(sales_array)

[120, 150, 300, 250, 90]
[120 150 300 250  90]


In [ ]:
#features = age, income, credit score
customer_matrix = np.array([
    [25, 50, 710],
    [45,95,700],
    [32,65, 620]
])
print(customer_matrix)

[[ 25  50 710]
 [ 45  95 700]
 [ 32  65 620]]


In [ ]:
#they are stored in float
zero_matrix = np.zeros((3, 4))
segment_matrix = np.arange(0,10,2)

In [ ]:
print(zero_matrix)
print(segment_matrix)
print(customer_matrix.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 2 4 6 8]
(3, 3)


In [ ]:
traffic = np.array((120, 500, 620, 480, 710, 911, 1000))
weekend_traffic = traffic[-2:]
print(weekend_traffic)

[ 911 1000]


In [ ]:
#senors readings
sensors = np.array([
    [12.1, 14.3, 15.2], #sensors 1
    [10.2, 11.4, 14.6], #sensors 2
    [19.5, 20.3, 11.4], #sensors 3
    [22.3, 21.3, 14.4]  #sensors 4
])

In [ ]:
specific_reading = sensors[2,1]
print(specific_reading)

20.3


In [ ]:
top_readings = sensors[0:2,:]
print(top_readings)

[[12.1 14.3 15.2]
 [10.2 11.4 14.6]]


In [ ]:
final_readings = sensors[:, 2]
print(final_readings)

[15.2 14.6 11.4 14.4]


In [ ]:
flat_temps = np.array((100, 90, 80, 98, 110, 100, 101, 110, 105, 104, 103, 102))
structured_temps = flat_temps.reshape(4, 3)
print("Structured Temperatures: \n",structured_temps)

Structured Temperatures: 
 [[100  90  80]
 [ 98 110 100]
 [101 110 105]
 [104 103 102]]


In [ ]:
celcius_temperature = ((structured_temps*32 - 32) * 5/9)
print("In celsius: \n", celcius_temperature.round(2))

In celsius: 
 [[1760.   1582.22 1404.44]
 [1724.44 1937.78 1760.  ]
 [1777.78 1937.78 1848.89]
 [1831.11 1813.33 1795.56]]


In [ ]:
score = np.array([
    [85, 95, 99],
    [13, 45, 50],
    [88, 91, 92]
])
print(score.min())
print(score.max())
print(score.mean().round(2))

13
99
73.11


In [ ]:
import time
size = 1_000_000
python_list = list(range(size))
numpy_array = np.arange(size)

In [ ]:
start_time = time.time()
python_list_result = [x*2 for x in python_list]
python_duration = time.time() - start_time

In [ ]:
start_time= time.time()
numpy_result = numpy_array*2
numpy_duration = time.time() - start_time

In [ ]:
print(f"time taken by standard python list:{python_duration} seconds")
print(f"time taken by nummpy list: {numpy_duration} seconds")
print(f" numpy is roughly {round(python_duration/numpy_duration)} seconds faster")

time taken by standard python list:0.07455897331237793 seconds
time taken by nummpy list: 0.005265712738037109 seconds
 numpy is roughly 14 seconds faster
