<a href="https://colab.research.google.com/github/user127386/AI-ML/blob/user127386/statistics_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import stats #since we dont have stats function in numpy we import scipy

In [ ]:
rent_prices = np.array([1200, 1350, 1400, 1200, 1300, 1400, 1500, 1550, 12000])

In [ ]:
mean_rent = np.mean(rent_prices)
median_rent = np.median(rent_prices)

In [ ]:
mode_result = stats.mode(rent_prices, keepdims=True) #keep dimension to keep the element in a row

In [ ]:
print(mode_result)
mode_rent = mode_result.mode[0]
mode_count = mode_result.count[0]

ModeResult(mode=array([1200]), count=array([2]))


In [ ]:
print(f"Mean of the array is: ${mean_rent.round(2)}")
print(f"Median of the array: ${median_rent}")
print(mode_rent)
print(mode_count)

Mean of the array is: $2544.44
Median of the array: $1400.0
1200
2


In [ ]:
city_a_temps = np.array([24,25,26,23,25])
city_b_temps = np.array([10,40,5,45,50])

In [ ]:
var_a = np.var(city_a_temps)
var_b = np.var(city_b_temps)

In [ ]:
std_a = np.std(city_a_temps)
std_b = np.std(city_b_temps)
print(f"City A: Variance = {var_a:.2f} | Standard Deviation = {std_a:.2f}")
print(f"City B: Variance = {var_b:.2f} | Standard Deviation = {std_b:.2f}")

City A: Variance = 1.04 | Standard Deviation = 1.02
City B: Variance = 350.00 | Standard Deviation = 18.71


In [ ]:
#covariance
#correlation

In [ ]:
marketing_spend = np.array([10,20,30,40,50])
online_sales = np.array([25,45,55,75,95])
complaints = np.array([15,12,10, 4, 2])

In [ ]:
cov_matrix = np.cov(marketing_spend, online_sales)
print(cov_matrix)
cov_matrix2 = np.cov(marketing_spend, complaints)
print(cov_matrix)
corr_matrix_posi = np.corrcoef(marketing_spend, online_sales)
print(corr_matrix_posi.round(2))
corr_matrix_nega = np.corrcoef(marketing_spend, complaints)
print(corr_matrix_nega.round(2))

[[250. 425.]
 [425. 730.]]
[[250. 425.]
 [425. 730.]]
[[1.   0.99]
 [0.99 1.  ]]
[[ 1.   -0.98]
 [-0.98  1.  ]]


In [ ]:
correlation_spend_sales = corr_matrix_posi[0,1]
print(correlation_spend_sales.round(4))
correlation_spend_complaints = corr_matrix_nega[0,1]
print(correlation_spend_complaints.round(4))

0.9948
-0.9848
